app:
  useCSRFProtection: 'true'
  security:
    referrerPolicy: 'origin'
  client-id:
services:
  frontend:
    name: 'FACT Frontend'
    url: 'http://localhost:3100'
  api:
    name: 'FACT API'
    url: 'http://localhost:8989'
    app-id:
  image-store:
    name: 'Image Store'
    url: 'https://factaat.blob.core.windows.net/images'
  mapit:
    name: 'MapIt API'
    url: 'https://mapit.mysociety.org'
health:
  timeout: 5000
  deadline: 15000
appInsights:
  instrumentationKey:
